server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    datasource:
      url: jdbc:mysql://localhost:3306/special_price
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.sql: debug
